[package]
name = "bevy-3d-capture"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.15", features=["jpeg"] }
bevy_image_export = "0.12.0"
